### PR TITLE
Correctly specify the font name and weight

### PR DESCRIPTION
**Pull request by timdream**
Please try not to made up your own font names for Open Sans. Specify the correct font weight instead.

### CODE REVIEW

**Comment by timdream** [comment]
@caseyyee ^

**Comment by timdream** [comment]
This is how Google Web Font does it.

http://fonts.googleapis.com/css?family=Open+Sans:400,700,600

**Comment by fabi1cazenave** [comment]
+1

**Comment by timdream** [comment]
We can even get rid of `font-family: 'Open Sans'` everywhere ...

**Comment by pivanov** [comment]
+1

**Comment by timdream** [comment]
@fabi1cazenave can you merge it?

**Comment by basiclines** [comment]
@fabi1cazenave we should remove/delete this old PR and get this `pull` section clean

**Pull request closed without merging**
