### PR TITLE
Update buttons changes

### PR DESCRIPTION
**Pull request by basiclines**
Applied changes from the feedback received in the last PR made to Gaia
Also splitting in two different components buttons/buttons_list

Please @fabi1cazenave @pivanov take a look!

Thx all!

PD: we need this to replicate the new classnames convention in to all the dialog-kind components

### CODE REVIEW

**Comment by basiclines** [comment]
@fabi1cazenave @pivanov  i need this merged asap please!

**Comment by jmcanterafonseca** [comment]
the changes look ok. merging

**Comment by pivanov** [comment]
I have only one note about :
... {
background-image: url(buttons/images/ui/danger.png);
background-color: #b70404;
}

is there a good reason about this ? because I think this is contrary to with our guidelines.

**Comment by basiclines** [comment]
@pivanov that is used for not redefining background position and tiling, just for use the inheritance

**Comment by pivanov** [comment]
ok ... that make sense :) I just want to be sure :)

**Pull request merged**
