### PR TITLE
Bug 905976 - (Followup #893707) - [bb][refactor] Headers

### PR DESCRIPTION
**Pull request by basiclines**
- Applied correct specification for rotation support from: 
  headers
- Removed `!important` declarations
- Moved `<h1>` tag at the top of the container (now using `display: flex`)
- Icons base crop area returned to 30px as is no longer needed to scale it down for rotation support

### CODE REVIEW

**Comment by rik** [comment]
Now that we use flex, I think we can get rid of the `<menu type="toolbar">` extra element. (And floats by extension)

I'd introduce a new class to differentiate the "left button" and put a `order: -1` on this new class.

Here's how the markup would look like (the `action-left` classname is obviously not the right name) :

``` html
<header class="bb-header">
  <h1>Inbox <em>(2)</em></h1>
  <button class="action action-left icon icon-menu">menu</button>
  <button class="action icon icon-edit">edit</button>
  <button class="action icon icon-add">add</button>
</header>
```

What do you think?

**Comment by pivanov** [comment]
+1 :) one element less

**Comment by basiclines** [comment]
Mmmm i don't think we must remove the `<menu>` tag, we should not be afraid on having an extra element.
I think it reinforces the semathic instead of adding a new classname. Also is way more scalable to have differenciated areas inside the header by a wrapper.
I'm not buying this if there isn't a reasonable reason to do it :D We gain more having it that without it.

EDIT: typo

**Comment by basiclines** [comment]
I imagine that we can merge this right? @pivanov @Rik

**Pull request merged**
