### PR TITLE
Header frame sizes

### PR DESCRIPTION
**Pull request by lightsofapollo**
Reduces header frame sizes so animations on elements that contain header BB will be async.
Note: I know this breaks at minimum the drawer BB, this is just my proposal / starting point.

### CODE REVIEW

**Comment by basiclines** [comment]
Hey @lightsofapollo could you explain a little bit more what this PR does and why is it needed?
Thx a lot!

**Comment by lightsofapollo** [comment]
@basiclines See https://github.com/mozilla-b2g/Gaia-UI-Building-Blocks/issues/38

Basically if your animation is not async its going to look a whole lot slower.

**Comment by basiclines** [comment]
@lightsofapollo  What does it means `async` in animations? i've been checking the github issue and i don't understand exactly what is the problem for having some part of the header outside the viewport, i mean, we do that kind of things to adjust the different application views (we have the non current views outside the viewport). 
Im ok merging this of course, i just want to learn what to do for avoiding this issues :D
Thx for your patience

**Comment by lightsofapollo** [comment]
@basiclines I am not the expert but here is my understanding of how it works:

To animate an element (transform, scale, transition) quickly we need to "pre-render" it what this means is the entire frame we wish to animate is painted and can be moved around in the GPU as one whole piece. When that element cannot be pre-rendered it is incrementally painted as it enters the viewport and we also need to do more work on the main thread as a consequence ( so it slows other stuff down ) the result is much lower FPS.

I didn't think about this before ( and I only discovered this by turning on log slow animations & paint flashing ) but in some cases negative/positive margin and text-indent would increase the size of the _frame_ which as I understand it may not be the same size as the _element_ ( as seen in the inspector ).

It may cause seizures but I highly recommend turning on paint flashing (in Settings -> About Phone -> "Flash repainted area") and playing around it will give you a much better idea how much work is going on.

**Comment by basiclines** [comment]
Ok, i see i will try to take a deeper look today! Thank you so much!

**Pull request closed without merging**
