### PR TITLE
Feature tabs

### PR DESCRIPTION
**Pull request by rnowm**
Replaced previous markup to adapt it to new visuals

### CODE REVIEW

**Comment by fabi1cazenave** [comment]
This looks OK to me, but why isn’t there any tab content? Is that on purpose?

E.g. [these CSS tabs](https://github.com/mozilla-b2g/Gaia-UI-Building-Blocks/blob/master/inprogress/tabs.html) work with a similar markup but really include tab content. Did you consider reusing them?

**Comment by fabi1cazenave** [comment]
Sorry if I’m wrong but these tabs still require some JS to work, right? Our current policy is that we won’t use any component from this repository if it requires some JS — it has to be fully declarative.

Did you check [the tabs I proposed](https://github.com/mozilla-b2g/Gaia-UI-Building-Blocks/blob/master/inprogress/tabs.html) which only require a few [CSS rules](https://github.com/mozilla-b2g/Gaia-UI-Building-Blocks/blob/master/inprogress/tabs.css) to work? If yes, please tell me why they can’t be used.

**Comment by rnowm** [comment]
@fabi1cazenave In the example they were at the top, and it took me a while to make the tabs work with ":target" when positioned at the bottom. Now both cases work.
I´m using: data-position="bottom" to move them to the bottom, if you remove it they change to top.

**Comment by basiclines** [comment]
@fabi1cazenave we should remove/delete this old PR and get this `pull` section clean

**Pull request closed without merging**
