### PR TITLE
files reordering 

### PR DESCRIPTION
**Pull request by pivanov**

### CODE REVIEW

**Comment by etiennesegonzac** [comment]
Can we do it without the sass files ? :)

**Comment by pivanov** [comment]
Yep we can. I made this at the request of Casey.

**Comment by etiennesegonzac** [comment]
I know we will end up with the css file anyway.
But for maintenance and collaboration on this I think vanilla CSS would have been better.

**Comment by fabi1cazenave** [comment]
+1 for vanilla CSS as we don’t have to deal with cross-browser things.
Nit: I’d prefer to keep the trailing brace `}` on its own line.

**Comment by etiennesegonzac** [comment]
+1 for the brace on its own line, like in Gaia

**Comment by pivanov** [comment]
+1 for vanila CSS we don't want to clean each time cross browser things like -webkit-, -o-, etc.

**Comment by jcarpenter** [comment]
Heh, +1 more for the brace on its own line. :D

**Comment by etiennesegonzac** [comment]
Whouhou, progress!

**Comment by pivanov** [comment]
Yeah :))) is not perfect but is something ...  :))) I hope you like it :))

Sent from my iPhone

Pavel Ivanov
phone : +359 885 448090
email : pivanov@mozilla.com

**Pull request merged**
